---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    # enable_mlag_ibgp_peering_vrfs: false
    mac_vrf_vni_base: 10000
    vrfs:
      - name: RED
        vrf_vni: 110
        vtep_diagnostic:
          loopback: 110
          loopback_ip_range: 10.255.110.0/24
        svis:
          - id: 110
            name: VRF_RED_VLAN_110
            tags:
              - dc1_pod1
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 112
            name: VRF_RED_VLAN_112
            tags:
              - dc1_pod2
            enabled: true
            ip_address_virtual: 10.1.12.1/24
          - id: 120
            name: VRF_RED_VLAN_120
            tags:
              - dc2_pod1
            enabled: true
            ip_address_virtual: 10.1.20.1/24
          - id: 122
            name: VRF_RED_VLAN_122
            tags:
              - dc2_pod2
            enabled: true
            ip_address_virtual: 10.1.22.1/24

      - name: BLUE
        vrf_vni: 210
        vtep_diagnostic:
          loopback: 210
          loopback_ip_range: 10.255.210.0/24
        svis:
          - id: 211
            name: VRF_BLUE_VLAN_211
            tags:
              - dc1_pod1
            enabled: true
            ip_address_virtual: 10.2.11.1/24
          - id: 113
            name: VRF_BLUE_VLAN_213
            tags:
              - dc1_pod2
            enabled: true
            ip_address_virtual: 10.2.13.1/24
          - id: 121
            name: VRF_BLUE_VLAN_221
            tags:
              - dc2_pod1
            enabled: true
            ip_address_virtual: 10.2.21.1/24
          - id: 123
            name: VRF_BLUE_VLAN_223
            tags:
              - dc2_pod2
            enabled: true
            ip_address_virtual: 10.2.23.1/24
