---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    # enable_mlag_ibgp_peering_vrfs: false
    mac_vrf_vni_base: 10000
    vrfs:
      - name: RED
        vrf_vni: 110
        vtep_diagnostic:
          loopback: 110
          loopback_ip_range: 10.255.110.0/24
        svis:
          - id: 111
            name: VRF_RED_VLAN_111
            # tags:
            #   - dc1_pod1
            enabled: true
            ip_address_virtual: 10.1.11.1/24
          - id: 112
            name: VRF_RED_VLAN_112
            # tags:
            #   - dc1_pod2
            enabled: true
            ip_address_virtual: 10.1.12.1/24



      - name: BLUE
        vrf_vni: 220
        vtep_diagnostic:
          loopback: 220
          loopback_ip_range: 10.255.220.0/24
        svis:
          - id: 213
            name: VRF_BLUE_VLAN_213
            # tags:
            #   - dc1_pod1
            enabled: true
            ip_address_virtual: 10.2.13.1/24
          - id: 214
            name: VRF_BLUE_VLAN_214
            # tags:
            #   - dc1_pod2
            enabled: true
            ip_address_virtual: 10.2.14.1/24
    l2vlans:
      - id: 120
        vni_override: 55120
        name: Motion_VLAN_120




